// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATaxAlPIaLrhtDa4rUW0oaWvi29RP68DU',
    appId: '1:1001693339339:web:4b04867f60cb962978c54e',
    messagingSenderId: '1001693339339',
    projectId: 'treknote-1',
    authDomain: 'treknote-1.firebaseapp.com',
    storageBucket: 'treknote-1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAEYLljGxlREtcFLDZzBoou_lFEzGUG30',
    appId: '1:1001693339339:android:ae5553ecdfe7ed4078c54e',
    messagingSenderId: '1001693339339',
    projectId: 'treknote-1',
    storageBucket: 'treknote-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEZFL3_XiA5qWZ902LB5WZoJV0pz3tHvk',
    appId: '1:1001693339339:ios:651c0bd21ec44efe78c54e',
    messagingSenderId: '1001693339339',
    projectId: 'treknote-1',
    storageBucket: 'treknote-1.firebasestorage.app',
    iosBundleId: 'com.example.treknoteflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEZFL3_XiA5qWZ902LB5WZoJV0pz3tHvk',
    appId: '1:1001693339339:ios:651c0bd21ec44efe78c54e',
    messagingSenderId: '1001693339339',
    projectId: 'treknote-1',
    storageBucket: 'treknote-1.firebasestorage.app',
    iosBundleId: 'com.example.treknoteflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATaxAlPIaLrhtDa4rUW0oaWvi29RP68DU',
    appId: '1:1001693339339:web:5d48398ac0f4ab0d78c54e',
    messagingSenderId: '1001693339339',
    projectId: 'treknote-1',
    authDomain: 'treknote-1.firebaseapp.com',
    storageBucket: 'treknote-1.firebasestorage.app',
  );
}
